language: python
sudo: false
python:
  - "2.7"
  - "3.6"
  - "3.7"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -U --no-cache-dir poetry
  - poetry install
  - poetry run python setup.py develop
  - poetry run python setup.py build sdist

# command to run tests
script: poetry run nosetests --verbosity 2 --with-spec --spec-color tests/unit tests/functional

# automated pypi releases
deploy:
  provider: pypi
  user: gabrielfalcao
  password:
    secure: E5KbnpQau7jv/mpHWAs19Y5zBaOHyBXRCGAsTS0S5lEOp/g8EEbjyt5rL7lcIeFAYarIds719BktC5iO+1AQbXOYicS5vDfiVRdLaJ5HPA4v6zyyQzwadFKSqE1Tv11AG9xkFDfBEPLTQmSrpI5cJIY5UoafDnMZe4CbLVETTw8=
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
